var mongoose = require('mongoose');
var ChampionSchema=mongoose.Schema({
    name:{
        type:String,
        require:true,
    },
    title:{
        type:String,
        require:true,
    },
    img:String,
    desc:String,
    tags:String,
    passive:{
        img:String,
        title:String,
        desc:String,
    },
    skill1:{
        img:String,
        title:String,
        desc:String,
    },
    skill2:{
        img:String,
        title:String,
        desc:String,
    },
    skill3:{
        img:String,
        title:String,
        desc:String,
    },
    skill4:{
        img:String,
        title:String,
        desc:String,
    }
})
var Champion=module.exports=mongoose.model('champions',ChampionSchema);